version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: circleci/python:3.6.6-jessie-browsers
    steps:
      - checkout
      - run: sudo .circleci/install_deps.sh
      - run: sudo .circleci/download_solc.sh
      - run: .circleci/run_test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
