version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gpresean/anyledger-wallet
    steps:
      - checkout
      - run: .circleci/run_test.sh
  build_zephyr:
    docker:
      - image: mohitagnihotri/anyledger
    steps:
      - checkout
      - run: .circleci/install_zephyr_env.sh
      - run: .circleci/build_zephyr_nrf52840_pca10056.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_zephyr
